import {StyleSheet} from 'react-native';
import {Colors} from '@/constants/colors';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    backgroundColor: Colors.WHITE,
    position: 'relative',
  },
  allContent: {
    width: '100%',
    backgroundColor: Colors.BACKGROUND_LIGHT,
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 20,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  buttonWrapper: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 16,
    paddingLeft: 16,
  },
  chevronLeft: {
    fontSize: 18,
    color: Colors.BACKGROUND_DARK,
    padding: 12,
  },
  sliderContainer: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    marginTop: 32,
  },
  animatedContainer: {
    width: '16%',
    height: 2.4,
    backgroundColor: Colors.BLACK,
    marginHorizontal: 4,
    borderRadius: 100,
  },
  infoAboutProduct: {
    paddingHorizontal: 16,
    marginTop: 6,
  },
  shoppingLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertica: 14,
  },
  shoppingCart: {
    fontSize: 18,
    color: Colors.BLUE,
    marginRight: 6,
  },
  shoppingLabelText: {
    fontSize: 12,
    color: Colors.BLUE,
  },
  ProductNameWrapper: {
    flexDirection: 'row',
    marginVertical: 4,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  productName: {
    fontSize: 24,
    fontWeight: '600',
    letterSpacing: 0.5,
    marginVertical: 4,
    color: Colors.BLACK,
    maxWidth: '84%',
  },
  linkOutline: {
    fontSize: 24,
    color: Colors.BLUE,
    backgroundColor: Colors.BLUE + 10,
    padding: 8,
    borderRadius: 100,
  },
  productDescription: {
    fontSize: 12,
    color: Colors.BLACK,
    fontWeight: '400',
    letterSpacing: 1,
    opacity: 0.5,
    lineHeight: 20,
    maxWidth: '85%',
    maxHeight: 44,
    marginBottom: 18,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 14,
    borderBottomColor: Colors.BACKGROUND_LIGHT,
    borderBottomWidth: 1,
    paddingBottom: 20,
  },
  pointLocation: {
    flexDirection: 'row',
    width: '80%',
    alignItems: 'center',
  },
  locationButtonWrapper: {
    color: Colors.BLUE,
    backgroundColor: Colors.BACKGROUND_LIGHT,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 100,
    marginRight: 10,
  },
  locationPin: {
    fontSize: 16,
    color: Colors.BLUE,
  },
  chevronRight: {
    fontSize: 22,
    color: Colors.BACKGROUND_DARK,
  },
  priceContainer: {
    paddingHorizontal: 16,
  },
  textPrice: {
    fontSize: 18,
    fontWeight: '500',
    maxWidth: '85%',
    color: Colors.BLACK,
    marginBottom: 4,
  },
  wrapperButtonAddToCart: {
    position: 'absolute',
    bottom: 20,
    height: '8%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonAddToCart: {
    width: '86%',
    height: '90%',
    backgroundColor: Colors.BLUE,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  status: {
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 1,
    color: Colors.WHITE,
    textTransform: 'uppercase',
  },
  productContainer: {
    height: 240,
    alignItems: 'center',
    justifyContent: 'center',
  },
  productImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
});
