import { StyleSheet} from 'react-native';
import {Colours} from '../../constants/colours';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    backgroundColor: Colours.WHITE,
    position: 'relative',
  },
  container1: {
    width: '100%',
    backgroundColor: Colours.BACKGROUND_LIGHT,
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 20,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  container2: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 16,
    paddingLeft: 16,
  },
  buttonContainer: {
    backgroundColor: Colours.WHITE,
    borderRadius: 10,
  },
  chevronLeft: {
    fontSize: 18,
    color: Colours.BACKGROUND_DARK,
    padding: 12,
  },
  container3: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    marginTop: 32,
  },
  animatedContainer: {
    width: '16%',
    height: 2.4,
    backgroundColor: Colours.BLACK,
    marginHorizontal: 4,
    borderRadius: 100,
  },
  container4: {
    paddingHorizontal: 16,
    marginTop: 6,
  },
  container5: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertica: 14,
  },
  shoppingCart: {
    fontSize: 18,
    color: Colours.BLUE,
    marginRight: 6,
  },
  text1: {
    fontSize: 12,
    color: Colours.BLUE,
  },
  container6: {
    flexDirection: 'row',
    marginVertical: 4,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  text2: {
    fontSize: 24,
    fontWeight: '600',
    letterSpacing: 0.5,
    marginVertical: 4,
    color: Colours.BLACK,
    maxWidth: '84%',
  },
  linkOutline: {
    fontSize: 24,
    color: Colours.BLUE,
    backgroundColor: Colours.BLUE + 10,
    padding: 8,
    borderRadius: 100,
  },
  text3: {
    fontSize: 12,
    color: Colours.BLACK,
    fontWeight: '400',
    letterSpacing: 1,
    opacity: 0.5,
    lineHeight: 20,
    maxWidth: '85%',
    maxHeight: 44,
    marginBottom: 18,
  },
  container7: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 14,
    borderBottomColor: Colours.BACKGROUND_LIGHT,
    borderBottomWidth: 1,
    paddingBottom: 20,
  },
  container8: {
    flexDirection: 'row',
    width: '80%',
    alignItems: 'center',
  },
  container9: {
    color: Colours.BLUE,
    backgroundColor: Colours.BACKGROUND_LIGHT,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 100,
    marginRight: 10,
  },
  locationPin: {
    fontSize: 16,
    color: Colours.BLUE,
  },
  chevronRight: {
    fontSize: 22,
    color: Colours.BACKGROUND_DARK,
  },
  container10: {
    paddingHorizontal: 16,
  },
  text4: {
    fontSize: 18,
    fontWeight: '500',
    maxWidth: '85%',
    color: Colours.BLACK,
    marginBottom: 4,
  },
  container11: {
    position: 'absolute',
    bottom: 20,
    height: '8%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  container12: {
    width: '86%',
    height: '90%',
    backgroundColor: Colours.BLUE,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text5: {
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 1,
    color: Colours.WHITE,
    textTransform: 'uppercase',
  },
  productContainer: {
    height: 240,
    alignItems: 'center',
    justifyContent: 'center',
  },
  productImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
});
