import {StyleSheet} from 'react-native';
import {Colors} from '../../constants/colors';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    backgroundColor: Colors.WHITE,
    position: 'relative',
  },
  container1: {
    width: '100%',
    flexDirection: 'row',
    paddingTop: 16,
    paddingHorizontal: 16,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  buttonContainer: {
    backgroundColor: Colors.WHITE,
    borderRadius: 10,
  },
  chevronLeft: {
    fontSize: 18,
    color: Colors.BACKGROUND_DARK,
    padding: 12,
  },
  text1: {
    fontSize: 14,
    color: Colors.BLACK,
    fontWeight: '400',
  },
  text2: {
    fontSize: 20,
    color: Colors.BLACK,
    fontWeight: '500',
    letterSpacing: 1,
    paddingTop: 20,
    paddingLeft: 16,
    marginBottom: 10,
  },
  container2: {
    paddingHorizontal: 16,
  },
  container3: {
    paddingHorizontal: 16,
    marginVertical: 10,
  },
  text3: {
    fontSize: 16,
    color: Colors.BLACK,
    fontWeight: '500',
    letterSpacing: 1,
    marginBottom: 20,
  },
  container4: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  container5: {
    flexDirection: 'row',
    width: '80%',
    alignItems: 'center',
  },
  container6: {
    color: Colors.BLUE,
    backgroundColor: Colors.BACKGROUND_LIGHT,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 10,
    marginRight: 18,
  },
  iconDelivery: {
    fontSize: 18,
    color: Colors.BLUE,
  },
  text4: {
    fontSize: 14,
    color: Colors.BLACK,
    fontWeight: '500',
  },
  text5: {
    fontSize: 12,
    color: Colors.BLACK,
    fontWeight: '400',
    lineHeight: 20,
    opacity: 0.5,
  },
  chevronRight: {
    fontSize: 22,
    color: Colors.BACKGROUND_DARK,
  },
  text6: {
    fontSize: 16,
    color: Colors.BLACK,
    fontWeight: '500',
    letterSpacing: 1,
    marginBottom: 20,
  },
  container8: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  container9: {
    flexDirection: 'row',
    width: '80%',
    alignItems: 'center',
  },
  container10: {
    color: Colors.BLUE,
    backgroundColor: Colors.BACKGROUND_LIGHT,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 10,
    marginRight: 18,
  },
  container11: {
    paddingHorizontal: 16,
    marginTop: 40,
    marginBottom: 80,
  },
  container12: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  container13: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 22,
  },
  container15: {
    position: 'absolute',
    bottom: 16,
    height: '8%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  container16: {
    width: '86%',
    height: '90%',
    backgroundColor: Colors.BLUE,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text7: {
    fontSize: 10,
    fontWeight: '900',
    color: Colors.BLUE,
    letterSpacing: 1,
  },
  text8: {
    fontSize: 14,
    color: Colors.BLACK,
    fontWeight: '500',
  },
  text9: {
    fontSize: 12,
    color: Colors.BLACK,
    fontWeight: '400',
    lineHeight: 20,
    opacity: 0.5,
  },
  text10: {
    fontSize: 16,
    color: Colors.BLACK,
    fontWeight: '500',
    letterSpacing: 1,
    marginBottom: 20,
  },
  text11: {
    fontSize: 12,
    fontWeight: '400',
    maxWidth: '80%',
    color: Colors.BLACK,
    opacity: 0.5,
  },
  text12: {
    fontSize: 12,
    fontWeight: '400',
    color: Colors.BLACK,
    opacity: 0.8,
  },
  text13: {
    fontSize: 18,
    fontWeight: '500',
    color: Colors.BLACK,
  },
  text14: {
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 1,
    color: Colors.WHITE,
    textTransform: 'uppercase',
  },
});
